In [3]:
import numpy as np

In [4]:
Reply = np.array([
    [1, 5, 5, 0, 3],
    [2, 0, 5, 0, 3],
    [0, 0, 0, 0, 0],
    [2, 0, 0, 4, 0],
    [0, 4, 2, 0, 0]
])

Reply

array([[1, 5, 5, 0, 3],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

In [5]:
Retweet = np.array([
    [0, 2, 4, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 3],
    [0, 2, 5, 0, 0]
])

Retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3],
       [0, 2, 5, 0, 0]])

In [6]:
Like = np.array([
    [2, 5, 1, 0, 3],
    [0, 0, 0, 0, 0],
    [0, 5, 0, 3, 3],
    [1, 0, 0, 4, 1],
    [0, 0, 9, 0, 0]
])

Like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

In [7]:
Post = np.array([2, 5, 10, 4, 3])

Post

array([ 2,  5, 10,  4,  3])

In [8]:
# (01) Trouver l'utilisateur qui répond (Reply) plus que les autres
reply_out = Reply.sum(axis=1)

reply_out.argmax()

0

In [9]:
# (02) Trouver l'utilisateur qui partage (Retweet) plus que les autres
retweet_out = Retweet.sum(axis=1)

retweet_out.argmax()

4

In [36]:
# (03) Trouver les utilisateurs qui ne répondent pas (Reply) et qui ne partagent pas (Retweet)
reply_retweet_out = reply_out + retweet_out
k=(reply_retweet_out == 0)
list(k).index(True)

2

In [11]:
# (04-a) Créer une matrice diagonale en utilisant la première dimention de la matrice des Likes

I = np.eye(Like.shape[0])

I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# (04-b) Afficher le nombre des Likes que chaque utilisateur fait pour ses propres tweets

nbr_self_likes = (I * Like).sum(axis=1)
#element wise
nbr_self_likes

array([2., 0., 0., 4., 0.])

In [13]:
# (05) Afficher le nombre des Likes que chaque utilisateur fait pour les tweets autre que les tien

like_out = Like.sum(axis=1)

nbr_notself_likes = like_out - nbr_self_likes

nbr_notself_likes

array([ 9.,  0., 11.,  2.,  9.])

In [39]:
# (06) Trouver les utilisateurs qui aiment leurs propres tweets plus qu'ils aiment les tweets des autres

like_more_self = nbr_notself_likes <  nbr_self_likes

list(like_more_self).index(True)

3

In [40]:
# (07) Calculer leur nombre

like_more_self.sum()

1

In [16]:
# (08) Afficher le nombre des interactions que chaque utilisateur a fait

reply_retweet_out + like_out

array([31, 10, 11, 15, 22])

In [17]:
# (01) Afficher le max des Likes que chaque utilisateur a reçu

max_likes_in = Like.max(axis=0)

max_likes_in

array([2, 5, 9, 4, 3])

In [18]:
# (02) Trouver les utilisateurs qui ont des likes pour tous leurs tweets au moins par une personne

max_likes_in == Post

array([ True,  True, False,  True,  True])

In [19]:
# (03) calculer le nombre des arcs entrants (ayant au moins une interaction)

in_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=0)

in_arcs

array([3, 3, 3, 2, 4])

In [20]:
# (04) calculer le nombre des arcs sortants (qui ont fait au moins une interaction)
out_arcs = ((Reply + Retweet + Like) > 0).astype(int).sum(axis=1)

out_arcs

array([4, 3, 3, 3, 2])